github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for all branches in this repo (defaults to false)
        branches: false
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
        # add a check to pull requests (defaults to true)
        addCheck: true
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
        addComment: false

image:
    file: .gitpod.dockerfile

tasks:
    - init: |
              npm install
              gp sync-done installation
      command: cargo test
    - init: gp sync-await installation
      command: stellar contract optimize --wasm target/wasm32-unknown-unknown/release/hello_world.wasm